[package]
name = "jj"
version = "0.1.0"
authors = ["taskie <t@skie.jp>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.40"
env_logger = "0.7.1"
log = "0.4.8"
quijine = { path = "../" }
serde_json = "1.0.64"
structopt = "0.3.14"
thiserror = "1.0.25"
