[package]
name = "jj"
version = "0.1.0"
authors = ["taskie <t@skie.jp>"]
edition = "2018"
publish = false

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
quijine = { path = "../" }
structopt = "0.3.14"
